'use strict';
// js/projects.js — Projects listing page logic.
// Detail pages are static HTML at projects/{slug}.html (generated by projects/_build.py).
// This file only handles: registry fetch, stats, filter bar, and card rendering.

const PROJ_REGISTRY = 'projects/index.json';

/* ── Fetch ──────────────────────────────────────────────── */

async function fetchProjectRegistry() {
  const res = await fetch(PROJ_REGISTRY + '?v=' + Date.now());
  if (!res.ok) throw new Error('Failed to load project registry');
  return res.json();
}

/* ── Stats ──────────────────────────────────────────────── */

function computeStats(projects) {
  const total      = projects.length;
  const completed  = projects.filter(p => p.status === 'completed').length;
  const categories = new Set(projects.map(p => p.category)).size;
  const recent     = projects.filter(p => p.date >= '2025-01-01').length;
  document.getElementById('stat-total').textContent      = total;
  document.getElementById('stat-completed').textContent  = completed;
  document.getElementById('stat-categories').textContent = categories;
  document.getElementById('stat-recent').textContent     = recent + '+';
}

/* ── Filter bar ─────────────────────────────────────────── */

let activeCategory = 'all';
let activeScope    = 'all';

function buildFilterBar(projects) {
  const cats   = ['All', ...new Set(projects.map(p => p.category))];
  const scopes = ['All', ...new Set(projects.map(p => p.scope))];

  const catRow   = document.getElementById('cat-filter-row');
  const scopeRow = document.getElementById('scope-filter-row');

  catRow.innerHTML = cats.map(c => {
    const val = c === 'All' ? 'all' : c;
    return `<button class="fbtn" aria-pressed="${val === 'all' ? 'true' : 'false'}"
              data-filter-cat="${val}"
              onclick="setCategory('${escapeHtml(val)}')">${escapeHtml(c)}</button>`;
  }).join('');

  scopeRow.innerHTML = scopes.map(s => {
    const val = s === 'All' ? 'all' : s;
    return `<button class="fbtn pfilter-row--secondary-btn" aria-pressed="${val === 'all' ? 'true' : 'false'}"
              data-filter-scope="${val}"
              onclick="setScope('${escapeHtml(val)}')">${escapeHtml(s)}</button>`;
  }).join('');
}

function setCategory(val) {
  activeCategory = val;
  document.querySelectorAll('[data-filter-cat]').forEach(b =>
    b.setAttribute('aria-pressed', String(b.dataset.filterCat === val)));
  applyFilters();
}

function setScope(val) {
  activeScope = val;
  document.querySelectorAll('[data-filter-scope]').forEach(b =>
    b.setAttribute('aria-pressed', String(b.dataset.filterScope === val)));
  applyFilters();
}

function applyFilters() {
  let anyVisible = false;
  document.querySelectorAll('.project-card').forEach(card => {
    const catMatch   = activeCategory === 'all' || card.dataset.category === activeCategory;
    const scopeMatch = activeScope    === 'all' || card.dataset.scope    === activeScope;
    const visible    = catMatch && scopeMatch;
    card.style.display = visible ? '' : 'none';
    if (visible) {
      anyVisible = true;
      card.classList.remove('visible');
      requestAnimationFrame(() => card.classList.add('visible'));
    }
  });
  const empty = document.getElementById('projects-empty');
  if (empty) empty.hidden = anyVisible;
}

/* ── Card renderer ──────────────────────────────────────── */

function renderProjectCard(project) {
  const card = document.createElement('article');
  card.className = 'project-card reveal';
  card.setAttribute('data-category', project.category);
  card.setAttribute('data-scope',    project.scope);
  card.setAttribute('data-status',   project.status);

  const outcomePills = project.outcomes.slice(0, 2).map(o =>
    `<div class="proj-outcome-pill">
      <span class="proj-outcome-metric">${escapeHtml(o.metric)}</span>
      <span class="proj-outcome-label">${escapeHtml(o.label)}</span>
    </div>`
  ).join('');

  const tagChips = project.tags.slice(0, 4).map(t =>
    `<span class="proj-tag">${escapeHtml(t)}</span>`
  ).join('');

  const href = `projects/${encodeURIComponent(project.slug)}.html`;

  card.innerHTML = `
    <a class="project-card-inner project-card-link" href="${href}">
      <div class="proj-header">
        <div class="proj-badges">
          <span class="proj-status proj-status--${escapeHtml(project.status)}">${escapeHtml(project.status)}</span>
          <span class="proj-category">${escapeHtml(project.category)}</span>
          <span class="proj-scope">${escapeHtml(project.scope)}</span>
          <span class="proj-duration">${escapeHtml(project.duration)}</span>
          ${project.featured ? '<span class="proj-featured">Featured</span>' : ''}
        </div>
        <time class="proj-date" datetime="${escapeHtml(project.date)}">${formatDate(project.date)}</time>
      </div>
      <h2 class="proj-title">${escapeHtml(project.title)}</h2>
      <p class="proj-summary">${escapeHtml(project.summary)}</p>
      <div class="proj-outcomes-row">${outcomePills}</div>
      <div class="proj-tags">${tagChips}</div>
      <span class="proj-card-cta">Read the case study →</span>
    </a>
  `;

  return card;
}

/* ── Reveal observer ────────────────────────────────────── */

function setupReveal() {
  const obs = new IntersectionObserver(entries => {
    entries.forEach(e => {
      if (e.isIntersecting) {
        e.target.classList.add('visible');
        obs.unobserve(e.target);
      }
    });
  }, { threshold: 0.06 });
  document.querySelectorAll('.reveal:not(.visible)').forEach(el => obs.observe(el));
}

/* ── Error display ──────────────────────────────────────── */

function showProjError(msg) {
  const list = document.getElementById('projects-list-sec');
  if (!list) return;
  list.insertAdjacentHTML('afterbegin',
    `<div class="blog-error" role="alert">Unable to load projects: ${escapeHtml(msg)}</div>`);
}

/* ── Init ───────────────────────────────────────────────── */

async function initProjects() {
  try {
    const data     = await fetchProjectRegistry();
    const projects = data.projects || [];

    computeStats(projects);
    buildFilterBar(projects);

    const list = document.getElementById('projects-list');
    projects.forEach(p => list.appendChild(renderProjectCard(p)));

    const emptyEl = document.getElementById('projects-empty');
    if (emptyEl) emptyEl.hidden = projects.length > 0;

    setupReveal();

    // Legacy hash deep-links (e.g. projects.html#sentinel-from-zero) → redirect to static page.
    const hash = location.hash.replace('#', '');
    if (hash && projects.some(p => p.slug === hash)) {
      location.replace(`projects/${encodeURIComponent(hash)}.html`);
    }
  } catch (err) {
    showProjError(err.message);
  }
}

document.addEventListener('DOMContentLoaded', initProjects);
